const keyboard = {
  TKL: [
    [
      { key: 'Esc', shift: 'Esc', active: false },
      { key: 'F1', shift: 'F1', active: false },
      { key: 'F2', shift: 'F2', active: false },
      { key: 'F3', shift: 'F3', active: false },
      { key: 'F4', shift: 'F4', active: false },
      { key: 'F5', shift: 'F5', active: false },
      { key: 'F6', shift: 'F6', active: false },
      { key: 'F7', shift: 'F7', active: false },
      { key: 'F8', shift: 'F8', active: false },
      { key: 'F9', shift: 'F9', active: false },
      { key: 'F10', shift: 'F10', active: false },
      { key: 'F11', shift: 'F11', active: false },
      { key: 'F12', shift: 'F12', active: false },
    ],
    [
      { key: '`', shift: '~', active: false },
      { key: '1', shift: '!', active: false },
      { key: '2', shift: '@', active: false },
      { key: '3', shift: '#', active: false },
      { key: '4', shift: '$', active: false },
      { key: '5', shift: '%', active: false },
      { key: '6', shift: '^', active: false },
      { key: '7', shift: '&', active: false },
      { key: '8', shift: '*', active: false },
      { key: '9', shift: '(', active: false },
      { key: '0', shift: ')', active: false },
      { key: '-', shift: '_', active: false },
      { key: '=', shift: '+', active: false },
      { key: 'Backspace', shift: 'Backspace', active: false },
    ],
    [
      { key: 'Tab', shift: 'Tab', active: false },
      { key: 'q', shift: 'Q', active: false },
      { key: 'w', shift: 'W', active: false },
      { key: 'e', shift: 'E', active: false },
      { key: 'r', shift: 'R', active: false },
      { key: 't', shift: 'T', active: false },
      { key: 'y', shift: 'Y', active: false },
      { key: 'u', shift: 'U', active: false },
      { key: 'i', shift: 'I', active: false },
      { key: 'o', shift: 'O', active: false },
      { key: 'p', shift: 'P', active: false },
      { key: '[', shift: '{', active: false },
      { key: ']', shift: '}', active: false },
      { key: '\\', shift: '|', active: false },
    ],
    [
      { key: 'CapsLock', shift: 'CapsLock', active: false },
      { key: 'a', shift: 'A', active: false },
      { key: 's', shift: 'S', active: false },
      { key: 'd', shift: 'D', active: false },
      { key: 'f', shift: 'F', active: false },
      { key: 'g', shift: 'G', active: false },
      { key: 'h', shift: 'H', active: false },
      { key: 'j', shift: 'J', active: false },
      { key: 'k', shift: 'K', active: false },
      { key: 'l', shift: 'L', active: false },
      { key: ';', shift: ':', active: false },
      { key: "'", shift: '"', active: false },
      { key: 'Enter', shift: 'Enter', active: false },
    ],
    [
      { key: 'Shift', shift: 'Shift', active: false },
      { key: 'z', shift: 'Z', active: false },
      { key: 'x', shift: 'X', active: false },
      { key: 'c', shift: 'C', active: false },
      { key: 'v', shift: 'V', active: false },
      { key: 'b', shift: 'B', active: false },
      { key: 'n', shift: 'N', active: false },
      { key: 'm', shift: 'M', active: false },
      { key: ',', shift: '<', active: false },
      { key: '.', shift: '>', active: false },
      { key: '/', shift: '?', active: false },
      { key: 'Shift', shift: 'Shift', active: false },
    ],
    [
      { key: 'Ctrl', shift: 'Ctrl', active: false },
      { key: 'Win', shift: 'Win', active: false },
      { key: 'Alt', shift: 'Alt', active: false },
      { key: 'Space', shift: 'Space', active: false },
      { key: 'Alt', shift: 'Alt', active: false },
      { key: 'Win', shift: 'Win', active: false },
      { key: 'Ctrl', shift: 'Ctrl', active: false },
    ],
  ],
}

export default keyboard
