const keyboard = {
  TKL: [
    [
      { key: 'Escape', shift: 'Escape', active: false, clicking: false },
      { key: 'F1', shift: 'F1', active: false, clicking: false },
      { key: 'F2', shift: 'F2', active: false, clicking: false },
      { key: 'F3', shift: 'F3', active: false, clicking: false },
      { key: 'F4', shift: 'F4', active: false, clicking: false },
      { key: 'F5', shift: 'F5', active: false, clicking: false },
      { key: 'F6', shift: 'F6', active: false, clicking: false },
      { key: 'F7', shift: 'F7', active: false, clicking: false },
      { key: 'F8', shift: 'F8', active: false, clicking: false },
      { key: 'F9', shift: 'F9', active: false, clicking: false },
      { key: 'F10', shift: 'F10', active: false, clicking: false },
      { key: 'F11', shift: 'F11', active: false, clicking: false },
      { key: 'F12', shift: 'F12', active: false, clicking: false },
    ],
    [
      { key: '\\', shift: '|', active: false, clicking: false },
      { key: '1', shift: '!', active: false, clicking: false },
      { key: '2', shift: '"', active: false, clicking: false },
      { key: '3', shift: '#', active: false, clicking: false },
      { key: '4', shift: '$', active: false, clicking: false },
      { key: '5', shift: '%', active: false, clicking: false },
      { key: '6', shift: '&', active: false, clicking: false },
      { key: '7', shift: '/', active: false, clicking: false },
      { key: '8', shift: '(', active: false, clicking: false },
      { key: '9', shift: ')', active: false, clicking: false },
      { key: '0', shift: '=', active: false, clicking: false },
      { key: "'", shift: '?', active: false, clicking: false },
      { key: '«', shift: '»', active: false, clicking: false },
      { key: 'Backspace', shift: 'Backspace', active: false, clicking: false },
    ],
    [
      { key: 'Tab', shift: 'Tab', active: false, clicking: false },
      { key: 'q', shift: 'Q', active: false, clicking: false },
      { key: 'w', shift: 'W', active: false, clicking: false },
      { key: 'e', shift: 'E', active: false, clicking: false },
      { key: 'r', shift: 'R', active: false, clicking: false },
      { key: 't', shift: 'T', active: false, clicking: false },
      { key: 'y', shift: 'Y', active: false, clicking: false },
      { key: 'u', shift: 'U', active: false, clicking: false },
      { key: 'i', shift: 'I', active: false, clicking: false },
      { key: 'o', shift: 'O', active: false, clicking: false },
      { key: 'p', shift: 'P', active: false, clicking: false },
      { key: '+', shift: '*', active: false, clicking: false },
      { key: '´', shift: '`', active: false, clicking: false },
      { key: '~', shift: '^', active: false, clicking: false },
    ],
    [
      { key: 'CapsLock', shift: 'CapsLock', active: false, clicking: false },
      { key: 'a', shift: 'A', active: false, clicking: false },
      { key: 's', shift: 'S', active: false, clicking: false },
      { key: 'd', shift: 'D', active: false, clicking: false },
      { key: 'f', shift: 'F', active: false, clicking: false },
      { key: 'g', shift: 'G', active: false, clicking: false },
      { key: 'h', shift: 'H', active: false, clicking: false },
      { key: 'j', shift: 'J', active: false, clicking: false },
      { key: 'k', shift: 'K', active: false, clicking: false },
      { key: 'l', shift: 'L', active: false, clicking: false },
      { key: 'ç', shift: 'Ç', active: false, clicking: false },
      { key: 'º', shift: 'ª', active: false, clicking: false },
      { key: 'Enter', shift: 'Enter', active: false, clicking: false },
    ],
    [
      { key: 'Shift', shift: 'Shift', active: false, clicking: false },
      { key: 'z', shift: 'Z', active: false, clicking: false },
      { key: 'x', shift: 'X', active: false, clicking: false },
      { key: 'c', shift: 'C', active: false, clicking: false },
      { key: 'v', shift: 'V', active: false, clicking: false },
      { key: 'b', shift: 'B', active: false, clicking: false },
      { key: 'n', shift: 'N', active: false, clicking: false },
      { key: 'm', shift: 'M', active: false, clicking: false },
      { key: ',', shift: ';', active: false, clicking: false },
      { key: '.', shift: ':', active: false, clicking: false },
      { key: '-', shift: '_', active: false, clicking: false },
      { key: 'Shift', shift: 'Shift', active: false, clicking: false },
    ],
    [
      { key: 'Ctrl', shift: 'Ctrl', active: false, clicking: false },
      { key: 'Win', shift: 'Win', active: false, clicking: false },
      { key: 'Alt', shift: 'Alt', active: false, clicking: false },
      { key: 'Space', shift: 'Space', active: false, clicking: false },
      { key: 'Alt', shift: 'Alt', active: false, clicking: false },
      { key: 'Win', shift: 'Win', active: false, clicking: false },
      { key: 'Ctrl', shift: 'Ctrl', active: false, clicking: false },
      { key: 'ArrowLeft', shift: 'ArrowLeft', active: false, clicking: false },
      { key: 'ArrowUp', shift: 'ArrowUp', active: false, clicking: false },
      { key: 'ArrowDown', shift: 'ArrowDown', active: false, clicking: false },
      {
        key: 'ArrowRight',
        shift: 'ArrowRight',
        active: false,
        clicking: false,
      },
    ],
  ],
}

export default keyboard
